In [136]:
# Pandas is used for data manipulation
import pandas as pd
import numpy as np
# Read in data and display first 5 rows
features = pd.read_csv('input.csv')
features.head(5)

,MES,YEAR,EURO,DOLAR,COBRE,DESEMPLEO,EXPMES,EXP2MES,ARROZ,HARINA,...,GASTOFINANCIERO,SERVICIODEEMISIONDECERTIFICADO,SERVICIODEFOTOCOPIADO,MEMBRESIAENASOCIACIONPROFESIONAL,SERVICIONOTARIAL,SERVICIOFUNERARIO,CUOTASENCENTROSDEPADRESYAPODERADOS,SERVICIODERESIDENCIASPARAADULTOSMAYORES,SERVICIODESALACUNA,IPC_REAL
0,1,2018,738.628478,605.858696,3.213429,6.5,0.1,0.1,101.03,99.46,...,98.55,100.0,98.20,99.62,98.01,98.92,97.13,96.78,97.38,98.980697
1,2,2018,736.229750,596.463500,3.177042,6.7,0.1,0.4,100.90,100.14,...,98.69,100.0,100.09,99.62,98.86,99.29,97.13,97.76,97.53,99.083350
2,3,2018,745.257046,604.142727,3.082405,6.9,0.3,0.2,100.18,99.95,...,99.12,100.0,100.38,99.62,99.64,99.34,100.57,98.93,100.32,99.282472
3,4,2018,737.628571,600.995714,3.093714,6.7,0.2,0.2,101.02,100.66,...,99.14,100.0,100.38,99.62,99.82,97.64,100.57,98.63,100.32,99.548142
4,5,2018,740.295042,626.791667,3.078727,7.0,0.2,0.2,100.33,100.45,...,99.76,100.0,100.06,99.62,100.01,98.89,100.57,99.46,100.35,99.805498

In [137]:
# One-hot encode the data using pandas get_dummies
IPC_reales=features['IPC_REAL']
features=features.drop('IPC_REAL',axis=1)
features = pd.concat([pd.get_dummies(features['MES']),features.drop('MES', axis=1)], axis=1)
features = pd.concat([pd.get_dummies(features['YEAR']),features.drop('YEAR', axis=1)], axis=1)
# Display the first 5 rows of the last 12 columns
print(features.shape)
features.head(5)

(14, 323)

,2018,2019,1,2,3,4,5,6,7,8,...,SEGUROS,GASTOFINANCIERO,SERVICIODEEMISIONDECERTIFICADO,SERVICIODEFOTOCOPIADO,MEMBRESIAENASOCIACIONPROFESIONAL,SERVICIONOTARIAL,SERVICIOFUNERARIO,CUOTASENCENTROSDEPADRESYAPODERADOS,SERVICIODERESIDENCIASPARAADULTOSMAYORES,SERVICIODESALACUNA
0,1,0,1,0,0,0,0,0,0,0,...,97.62,98.55,100.0,98.20,99.62,98.01,98.92,97.13,96.78,97.38
1,1,0,0,1,0,0,0,0,0,0,...,97.89,98.69,100.0,100.09,99.62,98.86,99.29,97.13,97.76,97.53
2,1,0,0,0,1,0,0,0,0,0,...,98.17,99.12,100.0,100.38,99.62,99.64,99.34,100.57,98.93,100.32
3,1,0,0,0,0,1,0,0,0,0,...,98.75,99.14,100.0,100.38,99.62,99.82,97.64,100.57,98.63,100.32
4,1,0,0,0,0,0,1,0,0,0,...,99.02,99.76,100.0,100.06,99.62,100.01,98.89,100.57,99.46,100.35

In [138]:
# Use numpy to convert to arrays
import numpy as np
# Labels are the values we want to predict
labels = np.array(features.iloc[:,20:323])
#print(labels)
#Remove the labels from the features
# axis 1 refers to the columns
features= features.drop(features.iloc[:,20:323], axis = 1)
#predecir= predecir.drop("VALOR", axis = 1)
# Saving feature names for later use
#feature_list = list(features.columns)
# Convert to numpy array
#features = np.array(features)

In [139]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size =0.25, random_state = 42)

In [140]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (10, 20)
Training Labels Shape: (10, 303)
Testing Features Shape: (4, 20)
Testing Labels Shape: (4, 303)

In [141]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(train_features, train_labels);

In [ ]:
pondera=[]
ff  = open('pond.csv', "rt")
r = csv.reader(ff)
for row in r :
    pondera.append(row[1])
pondera.pop(0)
ponderadores=[]
for i in pondera:
    ponderadores.append(float(i))

In [148]:
test_ind=[]
for fil in test_features.iterrows():
    test_ind.append(fil[0])
IPC_test=np.array(IPC_reales.iloc[test_ind])

In [152]:
# Use the forest's predict method on the test data
predictions = rf.predict(test_features)
IPC_predecidos=[]
for p in predictions:
    temp=[]
    for value in p:
        temp.append(float(value))
    IPC_predecidos.append(np.dot(np.array(temp),np.array(ponderadores))/100)
# Calculate the absolute errors
errors = np.array(abs(IPC_predecidos - IPC_test))
# Print out the mean absolute error (mae)
print('Mean Squared Error:', round(np.mean(np.square(errors)), 2), '')
print('Mean Absolute Error:', round(np.mean(errors), 2), '')

Mean Squared Error: 0.14
Mean Absolute Error: 0.36