In [42]:
# Pandas is used for data manipulation
import pandas as pd
import numpy as np
# Read in data and display first 5 rows
features = pd.read_csv('input.csv')
print(features.shape)
features.head(5)

(14, 420)

,MES,YEAR,EURO,DOLAR,COBRE,DESEMPLEO,EXPMES,EXP2MES,Maravilla $/litroPrecios a consumidor Supermercado,Vegetal $/litroPrecios a consumidor Supermercado,...,GASTOFINANCIERO,SERVICIODEEMISIONDECERTIFICADO,SERVICIODEFOTOCOPIADO,MEMBRESIAENASOCIACIONPROFESIONAL,SERVICIONOTARIAL,SERVICIOFUNERARIO,CUOTASENCENTROSDEPADRESYAPODERADOS,SERVICIODERESIDENCIASPARAADULTOSMAYORES,SERVICIODESALACUNA,IPC_REAL
0,1,2018,738.628478,605.858696,3.213429,6.5,0.1,0.1,1649.76,1484.24,...,98.55,100.0,98.20,99.62,98.01,98.92,97.13,96.78,97.38,98.980697
1,2,2018,736.229750,596.463500,3.177042,6.7,0.1,0.4,1639.75,1475.48,...,98.69,100.0,100.09,99.62,98.86,99.29,97.13,97.76,97.53,99.083350
2,3,2018,745.257046,604.142727,3.082405,6.9,0.3,0.2,1641.11,1469.47,...,99.12,100.0,100.38,99.62,99.64,99.34,100.57,98.93,100.32,99.282472
3,4,2018,737.628571,600.995714,3.093714,6.7,0.2,0.2,1634.09,1445.10,...,99.14,100.0,100.38,99.62,99.82,97.64,100.57,98.63,100.32,99.548142
4,5,2018,740.295042,626.791667,3.078727,7.0,0.2,0.2,1621.19,1433.77,...,99.76,100.0,100.06,99.62,100.01,98.89,100.57,99.46,100.35,99.805498

In [43]:
# One-hot encode the data using pandas get_dummies
IPC_reales=features['IPC_REAL']
features=features.drop('IPC_REAL',axis=1)
features = pd.concat([pd.get_dummies(features['MES']),features.drop('MES', axis=1)], axis=1)
features = pd.concat([pd.get_dummies(features['YEAR']),features.drop('YEAR', axis=1)], axis=1)
# Display the first 5 rows of the last 12 columns

In [44]:
cols=int(features.shape[1])

In [45]:
# Use numpy to convert to arrays
import numpy as np
# Labels are the values we want to predict
labels = np.array(features.iloc[:,cols-303:cols])
#print(labels)
#Remove the labels from the features
# axis 1 refers to the columns
features= features.drop(features.iloc[:,cols-303:cols], axis = 1)
features.head(5)
#predecir= predecir.drop("VALOR", axis = 1)
# Saving feature names for later use
#feature_list = list(features.columns)
# Convert to numpy array
#features = np.array(features)

,2018,2019,1,2,3,4,5,6,7,8,...,Margarina $/pote 500 gramosPrecios a consumidor Supermercado,Queso Chanco $/envase 1 kiloPrecios a consumidor Supermercado,Queso Gauda $/envase 1 kiloPrecios a consumidor Supermercado,Queso Mantecoso $/envase 1 kiloPrecios a consumidor Supermercado,Yoghurt (vainilla Ã³ frutilla) $/envase 125 gramosPrecios a consumidor Supermercado,Hallulla corriente $/kiloPrecios a consumidor Supermercado,Hallulla especial $/kiloPrecios a consumidor Supermercado,Hallulla integral $/kiloPrecios a consumidor Supermercado,Marraqueta $/kiloPrecios a consumidor Supermercado,Pan amasado $/kiloPrecios a consumidor Supermercado
0,1,0,1,0,0,0,0,0,0,0,...,1280.19,7123.69,6508.57,7575.02,177.26,1163.14,1450.68,1500.73,1233.21,1496.01
1,1,0,0,1,0,0,0,0,0,0,...,1277.63,7288.17,6442.39,7506.53,177.88,1170.90,1447.38,1491.51,1233.04,1553.64
2,1,0,0,0,1,0,0,0,0,0,...,1278.62,7182.81,6243.66,7352.02,179.09,1170.02,1444.01,1508.25,1232.38,1548.16
3,1,0,0,0,0,1,0,0,0,0,...,1301.10,7045.67,6354.38,7386.79,177.89,1176.29,1448.37,1510.95,1229.81,1559.82
4,1,0,0,0,0,0,1,0,0,0,...,1276.13,7086.00,6335.94,7653.62,178.79,1177.31,1448.41,1498.20,1233.45,1535.93

In [46]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
#train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size =0.25, random_state = 42)
train_features=features[:10]
test_features=features[10:]
train_labels=labels[:10]
test_labels=labels[10:]

In [47]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (10, 128)
Training Labels Shape: (10, 303)
Testing Features Shape: (4, 128)
Testing Labels Shape: (4, 303)

In [52]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision tree
rf = RandomForestRegressor(n_estimators = 1000, max_features=None)
# Train the model on training data
rf.fit(train_features, train_labels);

In [53]:
import csv
pondera=[]
ff  = open('pond.csv', "rt")
r = csv.reader(ff)
for row in r :
    pondera.append(row[1])
pondera.pop(0)
ponderadores=[]
for i in pondera:
    ponderadores.append(float(i))

In [54]:
test_ind=[]
for fil in test_features.iterrows():
    test_ind.append(fil[0])
IPC_test=np.array(IPC_reales.iloc[test_ind])

In [55]:
# Use the forest's predict method on the test data
predictions = rf.predict(test_features)
IPC_predecidos=[]
for p in predictions:
    temp=[]
    for value in p:
        temp.append(float(value))
    IPC_predecidos.append(np.dot(np.array(temp),np.array(ponderadores))/100)
# Calculate the absolute errors
errors = np.array(abs(IPC_predecidos - IPC_test))
# Print out the mean absolute error (mae)
print('Mean Squared Error:', round(np.mean(np.square(errors)), 2), '')
print('Mean Absolute Error:', round(np.mean(errors), 2), '')

Mean Squared Error: 0.5
Mean Absolute Error: 0.7

In [ ]:
#Valores Ãºltima canasta (2018): 0.14 0.36